version: "3.7"

services:
  bot:
    image: ghcr.io/darkflame72/craftybot:latest
    container_name: crafty
    restart: unless-stopped
    build: ./
    env_file:
      - '.env.local'
    ports:
      - "3000:3000"

